In [1]:
import torch

# Creating a 1D tensor
x = torch.tensor([1, 2, 3, 4])
print(x)

# Creating a 2D tensor (matrix)
y = torch.tensor([[1, 2], [3, 4]])
print(y)


tensor([1, 2, 3, 4])
tensor([[1, 2],
        [3, 4]])


In [2]:
print(x.shape)  # Output: torch.Size([4])
print(y.shape)  # Output: torch.Size([2, 2])
print(x.dtype)  # Data type of the tensor


torch.Size([4])
torch.Size([2, 2])
torch.int64


In [3]:
a = torch.tensor([5, 6, 7])
b = torch.tensor([1, 2, 3])

# Addition
print(a + b)

# Multiplication
print(a * b)

# Dot Product
print(torch.dot(a, b))


tensor([ 6,  8, 10])
tensor([ 5, 12, 21])
tensor(38)


In [4]:
import torch
print(torch.cuda.is_available())  # Returns True if CUDA (GPU) is available


False


In [5]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Creating a tensor and moving it to GPU
x = torch.tensor([1.0, 2.0, 3.0], device=device)
print(x)


tensor([1., 2., 3.])


In [8]:
import torch.nn as nn
conv_layer = nn.Conv2d(in_channels=1, out_channels=16, kernel_size=3)
print(conv_layer)


Conv2d(1, 16, kernel_size=(3, 3), stride=(1, 1))


In [9]:
import torch.nn as nn

layer = nn.Linear(in_features=3, out_features=2)  # 3 input neurons → 2 output neurons
print(layer)


Linear(in_features=3, out_features=2, bias=True)
